language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

script: ./gradlew -q -PbuildInfo.build.number=$TRAVIS_BUILD_NUMBER clean ass artifactoryPublish

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.gradle
