language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25

jdk:
  - oraclejdk8

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_script:
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew -q -s -d -PbuildInfo.build.number=$TRAVIS_BUILD_NUMBER clean ass cAT artifactoryPublish

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.gradle
